/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedFinanceiroRouteRouteImport } from './routes/_authenticated/financeiro/route'
import { Route as AuthenticatedAplicativoRouteRouteImport } from './routes/_authenticated/aplicativo/route'
import { Route as AuthenticatedUserAdminIndexRouteImport } from './routes/_authenticated/user-admin/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPresenceIndexRouteImport } from './routes/_authenticated/presence/index'
import { Route as AuthenticatedPlanosIndexRouteImport } from './routes/_authenticated/planos/index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedIptvIndexRouteImport } from './routes/_authenticated/iptv/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro/index'
import { Route as AuthenticatedDnsIndexRouteImport } from './routes/_authenticated/dns/index'
import { Route as AuthenticatedCouponsIndexRouteImport } from './routes/_authenticated/coupons/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAuditoriaIndexRouteImport } from './routes/_authenticated/auditoria/index'
import { Route as AuthenticatedAudienciaIndexRouteImport } from './routes/_authenticated/audiencia/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAplicativoIndexRouteImport } from './routes/_authenticated/aplicativo/index'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedUserAdminUserIdRouteImport } from './routes/_authenticated/user-admin/$userId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedFinanceiroRenovacoesRouteImport } from './routes/_authenticated/financeiro/renovacoes'
import { Route as AuthenticatedFinanceiroPagamentosRouteImport } from './routes/_authenticated/financeiro/pagamentos'
import { Route as AuthenticatedFinanceiroFunilRouteImport } from './routes/_authenticated/financeiro/funil'
import { Route as AuthenticatedFinanceiroContratacoesRouteImport } from './routes/_authenticated/financeiro/contratacoes'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAplicativoOcultarRouteImport } from './routes/_authenticated/aplicativo/ocultar'
import { Route as AuthenticatedAplicativoGeralRouteImport } from './routes/_authenticated/aplicativo/geral'
import { Route as AuthenticatedAplicativoPlatformRouteRouteImport } from './routes/_authenticated/aplicativo/$platform/route'
import { Route as AuthenticatedAplicativoPlatformIndexRouteImport } from './routes/_authenticated/aplicativo/$platform/index'
import { Route as AuthenticatedAplicativoPlatformSeriesRouteImport } from './routes/_authenticated/aplicativo/$platform/series'
import { Route as AuthenticatedAplicativoPlatformInicioRouteImport } from './routes/_authenticated/aplicativo/$platform/inicio'
import { Route as AuthenticatedAplicativoPlatformFilmesRouteImport } from './routes/_authenticated/aplicativo/$platform/filmes'
import { Route as AuthenticatedAplicativoPlatformAovivoRouteImport } from './routes/_authenticated/aplicativo/$platform/aovivo'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRouteRoute =
  AuthenticatedFinanceiroRouteRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAplicativoRouteRoute =
  AuthenticatedAplicativoRouteRouteImport.update({
    id: '/aplicativo',
    path: '/aplicativo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserAdminIndexRoute =
  AuthenticatedUserAdminIndexRouteImport.update({
    id: '/user-admin/',
    path: '/user-admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPresenceIndexRoute =
  AuthenticatedPresenceIndexRouteImport.update({
    id: '/presence/',
    path: '/presence/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosIndexRoute =
  AuthenticatedPlanosIndexRouteImport.update({
    id: '/planos/',
    path: '/planos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIptvIndexRoute = AuthenticatedIptvIndexRouteImport.update({
  id: '/iptv/',
  path: '/iptv/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedDnsIndexRoute = AuthenticatedDnsIndexRouteImport.update({
  id: '/dns/',
  path: '/dns/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsIndexRoute =
  AuthenticatedCouponsIndexRouteImport.update({
    id: '/coupons/',
    path: '/coupons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaIndexRoute =
  AuthenticatedAuditoriaIndexRouteImport.update({
    id: '/auditoria/',
    path: '/auditoria/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAudienciaIndexRoute =
  AuthenticatedAudienciaIndexRouteImport.update({
    id: '/audiencia/',
    path: '/audiencia/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAplicativoIndexRoute =
  AuthenticatedAplicativoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAplicativoRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedUserAdminUserIdRoute =
  AuthenticatedUserAdminUserIdRouteImport.update({
    id: '/user-admin/$userId',
    path: '/user-admin/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedFinanceiroRenovacoesRoute =
  AuthenticatedFinanceiroRenovacoesRouteImport.update({
    id: '/renovacoes',
    path: '/renovacoes',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroPagamentosRoute =
  AuthenticatedFinanceiroPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroFunilRoute =
  AuthenticatedFinanceiroFunilRouteImport.update({
    id: '/funil',
    path: '/funil',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedFinanceiroContratacoesRoute =
  AuthenticatedFinanceiroContratacoesRouteImport.update({
    id: '/contratacoes',
    path: '/contratacoes',
    getParentRoute: () => AuthenticatedFinanceiroRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAplicativoOcultarRoute =
  AuthenticatedAplicativoOcultarRouteImport.update({
    id: '/ocultar',
    path: '/ocultar',
    getParentRoute: () => AuthenticatedAplicativoRouteRoute,
  } as any)
const AuthenticatedAplicativoGeralRoute =
  AuthenticatedAplicativoGeralRouteImport.update({
    id: '/geral',
    path: '/geral',
    getParentRoute: () => AuthenticatedAplicativoRouteRoute,
  } as any)
const AuthenticatedAplicativoPlatformRouteRoute =
  AuthenticatedAplicativoPlatformRouteRouteImport.update({
    id: '/$platform',
    path: '/$platform',
    getParentRoute: () => AuthenticatedAplicativoRouteRoute,
  } as any)
const AuthenticatedAplicativoPlatformIndexRoute =
  AuthenticatedAplicativoPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAplicativoPlatformRouteRoute,
  } as any)
const AuthenticatedAplicativoPlatformSeriesRoute =
  AuthenticatedAplicativoPlatformSeriesRouteImport.update({
    id: '/series',
    path: '/series',
    getParentRoute: () => AuthenticatedAplicativoPlatformRouteRoute,
  } as any)
const AuthenticatedAplicativoPlatformInicioRoute =
  AuthenticatedAplicativoPlatformInicioRouteImport.update({
    id: '/inicio',
    path: '/inicio',
    getParentRoute: () => AuthenticatedAplicativoPlatformRouteRoute,
  } as any)
const AuthenticatedAplicativoPlatformFilmesRoute =
  AuthenticatedAplicativoPlatformFilmesRouteImport.update({
    id: '/filmes',
    path: '/filmes',
    getParentRoute: () => AuthenticatedAplicativoPlatformRouteRoute,
  } as any)
const AuthenticatedAplicativoPlatformAovivoRoute =
  AuthenticatedAplicativoPlatformAovivoRouteImport.update({
    id: '/aovivo',
    path: '/aovivo',
    getParentRoute: () => AuthenticatedAplicativoPlatformRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/aplicativo': typeof AuthenticatedAplicativoRouteRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/aplicativo/$platform': typeof AuthenticatedAplicativoPlatformRouteRouteWithChildren
  '/aplicativo/geral': typeof AuthenticatedAplicativoGeralRoute
  '/aplicativo/ocultar': typeof AuthenticatedAplicativoOcultarRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/financeiro/contratacoes': typeof AuthenticatedFinanceiroContratacoesRoute
  '/financeiro/funil': typeof AuthenticatedFinanceiroFunilRoute
  '/financeiro/pagamentos': typeof AuthenticatedFinanceiroPagamentosRoute
  '/financeiro/renovacoes': typeof AuthenticatedFinanceiroRenovacoesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/user-admin/$userId': typeof AuthenticatedUserAdminUserIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/aplicativo/': typeof AuthenticatedAplicativoIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/audiencia/': typeof AuthenticatedAudienciaIndexRoute
  '/auditoria/': typeof AuthenticatedAuditoriaIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/coupons/': typeof AuthenticatedCouponsIndexRoute
  '/dns/': typeof AuthenticatedDnsIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/iptv/': typeof AuthenticatedIptvIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/planos/': typeof AuthenticatedPlanosIndexRoute
  '/presence/': typeof AuthenticatedPresenceIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/user-admin/': typeof AuthenticatedUserAdminIndexRoute
  '/aplicativo/$platform/aovivo': typeof AuthenticatedAplicativoPlatformAovivoRoute
  '/aplicativo/$platform/filmes': typeof AuthenticatedAplicativoPlatformFilmesRoute
  '/aplicativo/$platform/inicio': typeof AuthenticatedAplicativoPlatformInicioRoute
  '/aplicativo/$platform/series': typeof AuthenticatedAplicativoPlatformSeriesRoute
  '/aplicativo/$platform/': typeof AuthenticatedAplicativoPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/aplicativo/geral': typeof AuthenticatedAplicativoGeralRoute
  '/aplicativo/ocultar': typeof AuthenticatedAplicativoOcultarRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/financeiro/contratacoes': typeof AuthenticatedFinanceiroContratacoesRoute
  '/financeiro/funil': typeof AuthenticatedFinanceiroFunilRoute
  '/financeiro/pagamentos': typeof AuthenticatedFinanceiroPagamentosRoute
  '/financeiro/renovacoes': typeof AuthenticatedFinanceiroRenovacoesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/user-admin/$userId': typeof AuthenticatedUserAdminUserIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/aplicativo': typeof AuthenticatedAplicativoIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/audiencia': typeof AuthenticatedAudienciaIndexRoute
  '/auditoria': typeof AuthenticatedAuditoriaIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/coupons': typeof AuthenticatedCouponsIndexRoute
  '/dns': typeof AuthenticatedDnsIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/iptv': typeof AuthenticatedIptvIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/planos': typeof AuthenticatedPlanosIndexRoute
  '/presence': typeof AuthenticatedPresenceIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/user-admin': typeof AuthenticatedUserAdminIndexRoute
  '/aplicativo/$platform/aovivo': typeof AuthenticatedAplicativoPlatformAovivoRoute
  '/aplicativo/$platform/filmes': typeof AuthenticatedAplicativoPlatformFilmesRoute
  '/aplicativo/$platform/inicio': typeof AuthenticatedAplicativoPlatformInicioRoute
  '/aplicativo/$platform/series': typeof AuthenticatedAplicativoPlatformSeriesRoute
  '/aplicativo/$platform': typeof AuthenticatedAplicativoPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/aplicativo': typeof AuthenticatedAplicativoRouteRouteWithChildren
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/aplicativo/$platform': typeof AuthenticatedAplicativoPlatformRouteRouteWithChildren
  '/_authenticated/aplicativo/geral': typeof AuthenticatedAplicativoGeralRoute
  '/_authenticated/aplicativo/ocultar': typeof AuthenticatedAplicativoOcultarRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/financeiro/contratacoes': typeof AuthenticatedFinanceiroContratacoesRoute
  '/_authenticated/financeiro/funil': typeof AuthenticatedFinanceiroFunilRoute
  '/_authenticated/financeiro/pagamentos': typeof AuthenticatedFinanceiroPagamentosRoute
  '/_authenticated/financeiro/renovacoes': typeof AuthenticatedFinanceiroRenovacoesRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/user-admin/$userId': typeof AuthenticatedUserAdminUserIdRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/_authenticated/aplicativo/': typeof AuthenticatedAplicativoIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/audiencia/': typeof AuthenticatedAudienciaIndexRoute
  '/_authenticated/auditoria/': typeof AuthenticatedAuditoriaIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/coupons/': typeof AuthenticatedCouponsIndexRoute
  '/_authenticated/dns/': typeof AuthenticatedDnsIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/iptv/': typeof AuthenticatedIptvIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/planos/': typeof AuthenticatedPlanosIndexRoute
  '/_authenticated/presence/': typeof AuthenticatedPresenceIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/user-admin/': typeof AuthenticatedUserAdminIndexRoute
  '/_authenticated/aplicativo/$platform/aovivo': typeof AuthenticatedAplicativoPlatformAovivoRoute
  '/_authenticated/aplicativo/$platform/filmes': typeof AuthenticatedAplicativoPlatformFilmesRoute
  '/_authenticated/aplicativo/$platform/inicio': typeof AuthenticatedAplicativoPlatformInicioRoute
  '/_authenticated/aplicativo/$platform/series': typeof AuthenticatedAplicativoPlatformSeriesRoute
  '/_authenticated/aplicativo/$platform/': typeof AuthenticatedAplicativoPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/aplicativo'
    | '/financeiro'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/aplicativo/$platform'
    | '/aplicativo/geral'
    | '/aplicativo/ocultar'
    | '/errors/$error'
    | '/financeiro/contratacoes'
    | '/financeiro/funil'
    | '/financeiro/pagamentos'
    | '/financeiro/renovacoes'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/user-admin/$userId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/aplicativo/'
    | '/apps/'
    | '/audiencia/'
    | '/auditoria/'
    | '/chats/'
    | '/coupons/'
    | '/dns/'
    | '/financeiro/'
    | '/help-center/'
    | '/iptv/'
    | '/messages/'
    | '/planos/'
    | '/presence/'
    | '/settings/'
    | '/user-admin/'
    | '/aplicativo/$platform/aovivo'
    | '/aplicativo/$platform/filmes'
    | '/aplicativo/$platform/inicio'
    | '/aplicativo/$platform/series'
    | '/aplicativo/$platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/aplicativo/geral'
    | '/aplicativo/ocultar'
    | '/errors/$error'
    | '/financeiro/contratacoes'
    | '/financeiro/funil'
    | '/financeiro/pagamentos'
    | '/financeiro/renovacoes'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/user-admin/$userId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/aplicativo'
    | '/apps'
    | '/audiencia'
    | '/auditoria'
    | '/chats'
    | '/coupons'
    | '/dns'
    | '/financeiro'
    | '/help-center'
    | '/iptv'
    | '/messages'
    | '/planos'
    | '/presence'
    | '/settings'
    | '/user-admin'
    | '/aplicativo/$platform/aovivo'
    | '/aplicativo/$platform/filmes'
    | '/aplicativo/$platform/inicio'
    | '/aplicativo/$platform/series'
    | '/aplicativo/$platform'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/aplicativo'
    | '/_authenticated/financeiro'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/aplicativo/$platform'
    | '/_authenticated/aplicativo/geral'
    | '/_authenticated/aplicativo/ocultar'
    | '/_authenticated/errors/$error'
    | '/_authenticated/financeiro/contratacoes'
    | '/_authenticated/financeiro/funil'
    | '/_authenticated/financeiro/pagamentos'
    | '/_authenticated/financeiro/renovacoes'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/user-admin/$userId'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/_authenticated/aplicativo/'
    | '/_authenticated/apps/'
    | '/_authenticated/audiencia/'
    | '/_authenticated/auditoria/'
    | '/_authenticated/chats/'
    | '/_authenticated/coupons/'
    | '/_authenticated/dns/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/help-center/'
    | '/_authenticated/iptv/'
    | '/_authenticated/messages/'
    | '/_authenticated/planos/'
    | '/_authenticated/presence/'
    | '/_authenticated/settings/'
    | '/_authenticated/user-admin/'
    | '/_authenticated/aplicativo/$platform/aovivo'
    | '/_authenticated/aplicativo/$platform/filmes'
    | '/_authenticated/aplicativo/$platform/inicio'
    | '/_authenticated/aplicativo/$platform/series'
    | '/_authenticated/aplicativo/$platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aplicativo': {
      id: '/_authenticated/aplicativo'
      path: '/aplicativo'
      fullPath: '/aplicativo'
      preLoaderRoute: typeof AuthenticatedAplicativoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-admin/': {
      id: '/_authenticated/user-admin/'
      path: '/user-admin'
      fullPath: '/user-admin/'
      preLoaderRoute: typeof AuthenticatedUserAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/presence/': {
      id: '/_authenticated/presence/'
      path: '/presence'
      fullPath: '/presence/'
      preLoaderRoute: typeof AuthenticatedPresenceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos/': {
      id: '/_authenticated/planos/'
      path: '/planos'
      fullPath: '/planos/'
      preLoaderRoute: typeof AuthenticatedPlanosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iptv/': {
      id: '/_authenticated/iptv/'
      path: '/iptv'
      fullPath: '/iptv/'
      preLoaderRoute: typeof AuthenticatedIptvIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/dns/': {
      id: '/_authenticated/dns/'
      path: '/dns'
      fullPath: '/dns/'
      preLoaderRoute: typeof AuthenticatedDnsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons/': {
      id: '/_authenticated/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof AuthenticatedCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria/': {
      id: '/_authenticated/auditoria/'
      path: '/auditoria'
      fullPath: '/auditoria/'
      preLoaderRoute: typeof AuthenticatedAuditoriaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audiencia/': {
      id: '/_authenticated/audiencia/'
      path: '/audiencia'
      fullPath: '/audiencia/'
      preLoaderRoute: typeof AuthenticatedAudienciaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aplicativo/': {
      id: '/_authenticated/aplicativo/'
      path: '/'
      fullPath: '/aplicativo/'
      preLoaderRoute: typeof AuthenticatedAplicativoIndexRouteImport
      parentRoute: typeof AuthenticatedAplicativoRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/user-admin/$userId': {
      id: '/_authenticated/user-admin/$userId'
      path: '/user-admin/$userId'
      fullPath: '/user-admin/$userId'
      preLoaderRoute: typeof AuthenticatedUserAdminUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/financeiro/renovacoes': {
      id: '/_authenticated/financeiro/renovacoes'
      path: '/renovacoes'
      fullPath: '/financeiro/renovacoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroRenovacoesRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/pagamentos': {
      id: '/_authenticated/financeiro/pagamentos'
      path: '/pagamentos'
      fullPath: '/financeiro/pagamentos'
      preLoaderRoute: typeof AuthenticatedFinanceiroPagamentosRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/funil': {
      id: '/_authenticated/financeiro/funil'
      path: '/funil'
      fullPath: '/financeiro/funil'
      preLoaderRoute: typeof AuthenticatedFinanceiroFunilRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/financeiro/contratacoes': {
      id: '/_authenticated/financeiro/contratacoes'
      path: '/contratacoes'
      fullPath: '/financeiro/contratacoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroContratacoesRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aplicativo/ocultar': {
      id: '/_authenticated/aplicativo/ocultar'
      path: '/ocultar'
      fullPath: '/aplicativo/ocultar'
      preLoaderRoute: typeof AuthenticatedAplicativoOcultarRouteImport
      parentRoute: typeof AuthenticatedAplicativoRouteRoute
    }
    '/_authenticated/aplicativo/geral': {
      id: '/_authenticated/aplicativo/geral'
      path: '/geral'
      fullPath: '/aplicativo/geral'
      preLoaderRoute: typeof AuthenticatedAplicativoGeralRouteImport
      parentRoute: typeof AuthenticatedAplicativoRouteRoute
    }
    '/_authenticated/aplicativo/$platform': {
      id: '/_authenticated/aplicativo/$platform'
      path: '/$platform'
      fullPath: '/aplicativo/$platform'
      preLoaderRoute: typeof AuthenticatedAplicativoPlatformRouteRouteImport
      parentRoute: typeof AuthenticatedAplicativoRouteRoute
    }
    '/_authenticated/aplicativo/$platform/': {
      id: '/_authenticated/aplicativo/$platform/'
      path: '/'
      fullPath: '/aplicativo/$platform/'
      preLoaderRoute: typeof AuthenticatedAplicativoPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedAplicativoPlatformRouteRoute
    }
    '/_authenticated/aplicativo/$platform/series': {
      id: '/_authenticated/aplicativo/$platform/series'
      path: '/series'
      fullPath: '/aplicativo/$platform/series'
      preLoaderRoute: typeof AuthenticatedAplicativoPlatformSeriesRouteImport
      parentRoute: typeof AuthenticatedAplicativoPlatformRouteRoute
    }
    '/_authenticated/aplicativo/$platform/inicio': {
      id: '/_authenticated/aplicativo/$platform/inicio'
      path: '/inicio'
      fullPath: '/aplicativo/$platform/inicio'
      preLoaderRoute: typeof AuthenticatedAplicativoPlatformInicioRouteImport
      parentRoute: typeof AuthenticatedAplicativoPlatformRouteRoute
    }
    '/_authenticated/aplicativo/$platform/filmes': {
      id: '/_authenticated/aplicativo/$platform/filmes'
      path: '/filmes'
      fullPath: '/aplicativo/$platform/filmes'
      preLoaderRoute: typeof AuthenticatedAplicativoPlatformFilmesRouteImport
      parentRoute: typeof AuthenticatedAplicativoPlatformRouteRoute
    }
    '/_authenticated/aplicativo/$platform/aovivo': {
      id: '/_authenticated/aplicativo/$platform/aovivo'
      path: '/aovivo'
      fullPath: '/aplicativo/$platform/aovivo'
      preLoaderRoute: typeof AuthenticatedAplicativoPlatformAovivoRouteImport
      parentRoute: typeof AuthenticatedAplicativoPlatformRouteRoute
    }
  }
}

interface AuthenticatedAplicativoPlatformRouteRouteChildren {
  AuthenticatedAplicativoPlatformAovivoRoute: typeof AuthenticatedAplicativoPlatformAovivoRoute
  AuthenticatedAplicativoPlatformFilmesRoute: typeof AuthenticatedAplicativoPlatformFilmesRoute
  AuthenticatedAplicativoPlatformInicioRoute: typeof AuthenticatedAplicativoPlatformInicioRoute
  AuthenticatedAplicativoPlatformSeriesRoute: typeof AuthenticatedAplicativoPlatformSeriesRoute
  AuthenticatedAplicativoPlatformIndexRoute: typeof AuthenticatedAplicativoPlatformIndexRoute
}

const AuthenticatedAplicativoPlatformRouteRouteChildren: AuthenticatedAplicativoPlatformRouteRouteChildren =
  {
    AuthenticatedAplicativoPlatformAovivoRoute:
      AuthenticatedAplicativoPlatformAovivoRoute,
    AuthenticatedAplicativoPlatformFilmesRoute:
      AuthenticatedAplicativoPlatformFilmesRoute,
    AuthenticatedAplicativoPlatformInicioRoute:
      AuthenticatedAplicativoPlatformInicioRoute,
    AuthenticatedAplicativoPlatformSeriesRoute:
      AuthenticatedAplicativoPlatformSeriesRoute,
    AuthenticatedAplicativoPlatformIndexRoute:
      AuthenticatedAplicativoPlatformIndexRoute,
  }

const AuthenticatedAplicativoPlatformRouteRouteWithChildren =
  AuthenticatedAplicativoPlatformRouteRoute._addFileChildren(
    AuthenticatedAplicativoPlatformRouteRouteChildren,
  )

interface AuthenticatedAplicativoRouteRouteChildren {
  AuthenticatedAplicativoPlatformRouteRoute: typeof AuthenticatedAplicativoPlatformRouteRouteWithChildren
  AuthenticatedAplicativoGeralRoute: typeof AuthenticatedAplicativoGeralRoute
  AuthenticatedAplicativoOcultarRoute: typeof AuthenticatedAplicativoOcultarRoute
  AuthenticatedAplicativoIndexRoute: typeof AuthenticatedAplicativoIndexRoute
}

const AuthenticatedAplicativoRouteRouteChildren: AuthenticatedAplicativoRouteRouteChildren =
  {
    AuthenticatedAplicativoPlatformRouteRoute:
      AuthenticatedAplicativoPlatformRouteRouteWithChildren,
    AuthenticatedAplicativoGeralRoute: AuthenticatedAplicativoGeralRoute,
    AuthenticatedAplicativoOcultarRoute: AuthenticatedAplicativoOcultarRoute,
    AuthenticatedAplicativoIndexRoute: AuthenticatedAplicativoIndexRoute,
  }

const AuthenticatedAplicativoRouteRouteWithChildren =
  AuthenticatedAplicativoRouteRoute._addFileChildren(
    AuthenticatedAplicativoRouteRouteChildren,
  )

interface AuthenticatedFinanceiroRouteRouteChildren {
  AuthenticatedFinanceiroContratacoesRoute: typeof AuthenticatedFinanceiroContratacoesRoute
  AuthenticatedFinanceiroFunilRoute: typeof AuthenticatedFinanceiroFunilRoute
  AuthenticatedFinanceiroPagamentosRoute: typeof AuthenticatedFinanceiroPagamentosRoute
  AuthenticatedFinanceiroRenovacoesRoute: typeof AuthenticatedFinanceiroRenovacoesRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteRouteChildren: AuthenticatedFinanceiroRouteRouteChildren =
  {
    AuthenticatedFinanceiroContratacoesRoute:
      AuthenticatedFinanceiroContratacoesRoute,
    AuthenticatedFinanceiroFunilRoute: AuthenticatedFinanceiroFunilRoute,
    AuthenticatedFinanceiroPagamentosRoute:
      AuthenticatedFinanceiroPagamentosRoute,
    AuthenticatedFinanceiroRenovacoesRoute:
      AuthenticatedFinanceiroRenovacoesRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteRouteWithChildren =
  AuthenticatedFinanceiroRouteRoute._addFileChildren(
    AuthenticatedFinanceiroRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAplicativoRouteRoute: typeof AuthenticatedAplicativoRouteRouteWithChildren
  AuthenticatedFinanceiroRouteRoute: typeof AuthenticatedFinanceiroRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedUserAdminUserIdRoute: typeof AuthenticatedUserAdminUserIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAudienciaIndexRoute: typeof AuthenticatedAudienciaIndexRoute
  AuthenticatedAuditoriaIndexRoute: typeof AuthenticatedAuditoriaIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCouponsIndexRoute: typeof AuthenticatedCouponsIndexRoute
  AuthenticatedDnsIndexRoute: typeof AuthenticatedDnsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedIptvIndexRoute: typeof AuthenticatedIptvIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedPlanosIndexRoute: typeof AuthenticatedPlanosIndexRoute
  AuthenticatedPresenceIndexRoute: typeof AuthenticatedPresenceIndexRoute
  AuthenticatedUserAdminIndexRoute: typeof AuthenticatedUserAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAplicativoRouteRoute:
    AuthenticatedAplicativoRouteRouteWithChildren,
  AuthenticatedFinanceiroRouteRoute:
    AuthenticatedFinanceiroRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedUserAdminUserIdRoute: AuthenticatedUserAdminUserIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAudienciaIndexRoute: AuthenticatedAudienciaIndexRoute,
  AuthenticatedAuditoriaIndexRoute: AuthenticatedAuditoriaIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCouponsIndexRoute: AuthenticatedCouponsIndexRoute,
  AuthenticatedDnsIndexRoute: AuthenticatedDnsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedIptvIndexRoute: AuthenticatedIptvIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedPlanosIndexRoute: AuthenticatedPlanosIndexRoute,
  AuthenticatedPresenceIndexRoute: AuthenticatedPresenceIndexRoute,
  AuthenticatedUserAdminIndexRoute: AuthenticatedUserAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRoute
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRoute,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
